### ISSUE TITLE
Supporting iqtree2: option mapping provided here

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/arbow#11]
```
iqtree -s aln-2020-05-10-175800.aln -pre tree-2020-05-10-175800 -mset HKY,TIM2,GTR -mfreq F -mrate G,R -bb 1000 -alrt 1000 -nt 8 -fconst 8668,5273,5646,9324
```
```
-s    same
-pre    --prefix
-mset   --mset
-mfreq   --mfreq                           CHNAGED MEANDING?
-mrate   --mrate
-bb    -B, --ufboot
-alrt    --alrt  
-nt     -T
-fconst   same
-o    same  (outgroup ID)
```

**Comment by tseemann** [comment]
iqtree could be v1 or v2
iqtree2 is v2
--version works on both and parses the same

**Comment by tseemann** [comment]
```
  --mfreq STR,...      List of state frequencies
```

seems to be a different optioon now?

**Comment by tseemann** [comment]
--mrate STR,...      List of rate heterogeneity among sites
                       (e.g. -mrate E,I,G,I+G,R is used for -m MF)

this seems to not work either

qtree2 --mrate F,G --mset HKY,TIM2,GTR
Invalid "--mrate" option. (edited) 
9:51
iqtree2 --help | grep mrate
  --mrate STR,...      List of rate heterogeneity among sites
                       (e.g. -mrate E,I,G,I+G,R is used for -m MF)
9:51
oh sorry - "F" is not valid, not the --mrate itself
9:51
what is iqtree2 equiv of F ?

**Comment by andersgs** [comment]
IQTRee2 is now supported as of version 0.6.0
