### ISSUE TITLE
Allow --mm to be a float -> proportion?

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/arbow#4]
If -mm is (0,1) then treat as a float proportion 
If (1, Inf) then treat as integer abolsutite count?

```
  -mm, --max-missing INTEGER     Remove sites with 'mm' missing sites or more
                                 [default: 20]
```

**Comment by andersgs** [comment]
yeah... the same could be done for `-x`

**Comment by andersgs** [comment]
Almost there... Just needs some testing.

**Comment by andersgs** [comment]
Version 0.6.0 has options `-c` for counts and `-x` for proportion.
